### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Salokyn** [linuxserver/docker-webgrabplus#35] opened 2021-02-12 09:53 UTC
Hi,

I use webgrabplus container on Libreelec on RPi4

## Expected Behavior
It should work

## Current Behavior
Crash with this error

```
            WebGrab+Plus/w MDB & REX Postprocess -- version V3.1.5.0            

                                Jan van Straaten                                
                             Francis De Paemeleere                              

            thanks to Paul Weterings and all the contributing users             
--------------------------------------------------------------------------------

Job started at 12/02/2021 04:47:08
Checking License ..
For License request/update data, see WGLicense.log.txt
Job finished at 12/02/2021 04:47:20 done in 11s

Object reference not set to an instance of an object.

  at  . ..ctor (System.String ) [0x01367] in <19bf6f65ef814889813448233e5627e5>:0 
  at  .―.  (System.String[] ) [0x00351] in <19bf6f65ef814889813448233e5627e5>:0 
Unhandled Exception
For detailed info, see log file /config/WebGrab++.log.txt
Execution stopped
```

## Steps to Reproduce
1. Install Webgrabplus addon from libreelec library
2. Run `docker container exec webgrabplus /bin/bash /defaults/update.sh`

## Environment
**OS:** LibreELEC (official): 9.2.6
**CPU architecture:** RPi4.arm
**How docker service was installed:** From linuxserver.io kodi addon library

## Command used to create docker container (run/create/compose/screenshot)
`docker container exec webgrabplus /bin/bash /defaults/update.sh`

## Docker logs
-empty-

**Comment by Salokyn** [comment] 2021-02-12 09:56
```
# docker image ls
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
linuxserver/webgrabplus            latest              98dc4e8e385f        7 days ago          243MB
```

**Comment by Salokyn** [comment] 2021-02-12 13:22
Well "lsio" network that uses Libreelec addons has no access to the internet...

**Comment by aptalca** [comment] 2021-02-12 14:02
Do you have a vpn addon or something like that messing with the network interfaces?

**Comment by Salokyn** [comment] 2021-02-12 14:58
No, but I activated firewall in Libreelec options.

When deactivated that works. I guess iptables config did not took that "lsio" network into account...

**Comment by aptalca** [comment] 2021-02-12 15:15
Then you'll have to fix your firewall/iptables. That's a system issue specific to your setup and would block all user defined docker networks.

Closing as it is not a bug with webgrabplus. Feel free to drop by our discord or discourse to discuss further

**Closed by aptalca** 2021-02-12 15:15 UTC
